spring:
  application:
    name: mcp-betobot
  threads:
    virtual:
      enabled: true

  ai:
    google:
      genai:
        api-key: ${GOOGLE_API_KEY}
    mcp:
      server:
        protocol: STREAMABLE
      client:
        type: ASYNC
        enabled: true
        sse:
          connections:
            github:
              url: http://host.docker.internal:9090
              sse-endpoint: /sse


logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG