spring:
  application:
    name: mcp-betobot
  threads:
    virtual:
      enabled: true

  ai:
    google:
      genai:
        api-key: ${GOOGLE_API_KEY}
        embedding:
          text:
            options:
              model: models/gemini-embedding-2
              dimensions: 1536
          api-key: ${GOOGLE_API_KEY}

    mcp:
      client:
        streamable-http:
          connections:
            github:
              url: ${GITHUB_MCP_SERVER_ADDRESS}

    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000
        initialize-schema: true
        remove-existing-vector-store-table: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

github-app:
  clientId: ${GITHUB_CLIENT_ID}
  installationId: ${GITHUB_APP_INSTALL_ID}
  key: ${GITHUB_APP_KEY_PATH}

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG